quarkus.http.port=8081
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.hibernate-orm.database.generation=update


# ---- DEV: H2 em arquivo (./data), não precisa de Docker ----
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:file:./data/catalogo;DB_CLOSE_DELAY=-1
%dev.quarkus.datasource.devservices.enabled=false
%dev.quarkus.live-reload.instrumentation=false
# ---- PROD: PostgreSQL (variáveis de ambiente) ----
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/fruteira}
%prod.quarkus.datasource.username=${DB_USER:postgres}
%prod.quarkus.datasource.password=${DB_PASS:fruteira}
