quarkus.http.port=8084
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.hibernate-orm.database.generation=update

%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:file:./data/retaguarda;DB_CLOSE_DELAY=-1
%dev.quarkus.datasource.devservices.enabled=false
%dev.quarkus.live-reload.instrumentation=false
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/fruteira}
%prod.quarkus.datasource.username=${DB_USER:postgres}
%prod.quarkus.datasource.password=${DB_PASS:fruteira}
